
navigation_manipulation_mode_v2_demonstrations = (
    "Here are some examples of how to complete a task using both navigation and manipulation actions. Each example includes a task description, step-by-step reasoning, and the sequence of actions taken to accomplish the task. Use these examples as a guide for similar tasks.\n"
    "Example 1. \n"
    "Task: Go to the eggplant plants and get a close-up view of an eggplant with the tip camera.\n"
    "Reasoning: \nI need to check the occupancy map to see where the eggplant plants are located.\n"
    "I obtained the occupancy map and found that there are some eggplant plants at (2.0, 4.0) on the map. I will set the manipulator to the home position for safe navigation.\n"
    "The manipulator is now in the home position. I will navigate to (2.0, 4.0).\n"
    "I have reached the target location. Now I will check the front camera image to see if there are eggplants in front of me.\n"
    "The front camera image shows that there are eggplants ahead. I will move the manipulator to the scanning position to get a better view.\n"
    "Now I will check the tip camera image to see if I can see an eggplant.\n"
    "The tip camera image shows an eggplant partially visible at the bottom. I will move the tip camera downward to get a better view.\n"
    "The tip camera image now shows an eggplant clearly at pixel coordinates (100, 350). I will center the tip camera on these coordinates.\n"
    "Now the eggplant is visible in the center of the image, but I could get closer. I will move the tip camera forward.\n"
    "I will try to move further forward to get closer to the eggplant.\n"
    "After failing to move forward, the eggplant is now clearly visible. I will notify the human about it.\n"

    "Example 2. \n"
    "Task: Go to the eggplant plants and get a close-up view of an eggplant with the tip camera.\n"
    "Reasoning: \nI need to check the occupancy map to see where the eggplant plants are located.\n"
    "I obtained the occupancy map and found that there are some eggplant plants at (3.0, -2.0) on the map. "
    "I will set the manipulator to the home position for safe navigation.\n"
    "The manipulator is now in the home position. I will navigate to (3.0, -2.0).\n"
    "I have reached the target location. Now I will check the front camera image to see if there are eggplants in front of me.\n"
    "The front camera image shows a plant, but it doesn't look like an eggplant plant. I will start a scanning sequence by rotating in place 90 degrees at a time to the right until finding eggplants. \n"
    "The new front camera image doesn't show eggplants. I will rotate 90 degrees a second time to the right as part of the scanning sequence.\n"
    "The new front camera image doesn't show eggplants. I will rotate 90 degrees a third and final time to the right to complete the scanning sequence.\n"
    "The front camera image shows an eggplant now. I will set the manipulator to scanning position...\n"
    
    "Example 3. \n"
    "Task: Go to the eggplant plant and get a close-up view of an eggplant with the tip camera.\n"
    "Reasoning: \nI need to check the occupancy map to see where the eggplant plants are located.\n"
    "I obtained the occupancy map and found that there are some eggplant plants at (3.0, 4.0) on the map. I will set the manipulator to the home position for safe navigation.\n"
    "The manipulator is now in the home position. I will navigate to (3.0, 4.0).\n"
    "I have reached the target location. Now I will check the front camera image to see if there are eggplant plants in front of me.\n"
    "The front camera image shows that there are eggplant plants ahead. I will move the manipulator to the scanning position to get a better view.\n"
    "Now I will check the tip camera image to see if I can see an eggplant.\n"
    "The tip camera image now shows an eggplant clearly at pixel coordinates (100, 350). I will center the tip camera on these coordinates.\n"
    "After trying to center the eggplant, it is not centered yet. I will try to center the tip camera at pixel coordinates (400,300) where the eggplant is.\n"
    "Now the eggplant is visible in the center of the image, but I could get closer. I will move the tip camera forward.\n"
    "I will try to move further forward to get closer to the eggplant.\n"
    "After moving the camera forward, the eggplant is now clearly visible. I will notify the human about it.\n"

    "Example 4. \n"
    "Task: Go to the eggplant plants and get a close-up view of an eggplant  with the tip camera.\n"
    "Reasoning: \nI need to check the occupancy map to see where the eggplant plants are located.\n"
    "I obtained the occupancy map and found that there are some eggplant plants at (2.0, 4.0) on the map. "
    "I will set the manipulator to the home position for safe navigation.\n"
    "The manipulator is now in the home position. I will navigate to (2.0, 4.0).\n"
    "I have reached the target location. Now I will check the front camera image to see if there are eggplants in front of me.\n"
    "The front camera image shows that there are eggplants ahead. I will move the manipulator to the scanning position to get a better view.\n"
    "Now I will check the tip camera image to see if I can see an eggplant .\n"
    "The tip camera image shows an eggplant partially visible at the bottom. I will move the tip camera downward to get a better view.\n"
    "Moving the tip camera downward failed. I will center the bottom part of the image at coordinates (320, 480) as a second alternative.\n"
    "The tip camera image now shows an eggplant  clearly at pixel coordinates (300, 450). I will center the tip camera on these coordinates...\n"

    "Example 5. \n"
    "Task: Go to the eggplant plants and get a close-up view of an eggplant  with the tip camera.\n"
    "Reasoning: \nI need to check the occupancy map to see where the eggplant plants are located.\n"
    "I obtained the occupancy map and found that there are some eggplant plants at (1.0, 2.0) on the map. "
    "I will set the manipulator to the home position for safe navigation.\n"
    "The manipulator is now in the home position. I will navigate to (1.0, 2.0).\n"
    "I have reached the target location. Now I will check the front camera image to see if there are eggplants in front of me.\n"
    "There are some eggplant plants visible in the front camera image, but they are far away. Considering the potential actions shown on the image, I will execute action 4 which takes me closer to an eggplant plant. \n"
    "The new front camera image shows an eggplant plant close to me. I will move the manipulator to the scanning position to get a better view...\n"

    "Example 6. \n"
    "Task: Go to the eggplant plants and get a close-up view of an eggplant  with the tip camera.\n"
    "Reasoning: \nI need to check the occupancy map to see where the eggplant plants are located.\n"
    "I obtained the occupancy map and found that there are some eggplant plants at (4.5, 1.0) on the map. "
    "I will set the manipulator to the home position for safe navigation.\n"
    "The manipulator is now in the home position. I will navigate to (4.5, 1.0).\n"
    "I have reached the target location. Now I will check the front camera image to see if there are eggplant plants in front of me.\n"
    "There are some eggplant plants visible in the front camera image, but they are in the background. I will check the front camera image with potential actions to choose one that takes me closer to an eggplant plant. \n"
    "The front camera image shows no potential actions. I will check the global occupancy map to look for another navigation goal\n"
    "The occupancy map shows another cluster of eggplants at (2.0, 4.0). I will navigate to (2.0, 4.0)...\n"

)


navigation_manipulation_mode_v3_demonstrations = (
    "Here are some examples of how to complete a task using both navigation and manipulation actions. Each example includes a task description, step-by-step reasoning, and the sequence of actions taken to accomplish the task. Use these examples as a guide for similar tasks.\n"
    "Example 1. \n"
    "Task: Go to the eggplant plant and get a close-up view of an eggplant with the tip camera.\n"
    "Reasoning: \nI need to check the occupancy map to see where the eggplant plants are located.\n"
    "I obtained the occupancy map and found that there are some eggplant plants at (2.0, 4.0) on the map. I will set the manipulator to the home position for safe navigation.\n"
    "The manipulator is now in the home position. I will navigate to (2.0, 4.0).\n"
    "I have reached the target location. Now I will check the front camera image to see if there are eggplant plants in front of me.\n"
    "The front camera image shows that there are eggplant plants ahead. I will move the manipulator to the scanning position to get a better view.\n"
    "Now I will check the tip camera image to see if I can see an eggplant.\n"
    "The tip camera image shows an eggplant partially visible at the bottom. I will move the tip camera downward to get a better view.\n"
    "The tip camera image now shows an eggplant clearly at pixel coordinates (100, 350). I will center the tip camera on these coordinates.\n"
    "Now the eggplant is visible in the center of the image, but I could get closer. I will move the tip camera forward.\n"
    "I will try to move further forward to get closer to the eggplant.\n"
    "After failing to move forward, the eggplant is now clearly visible. I will notify the human about it.\n"

    "Example 2. \n"
    "Task: Go to the eggplant plants and get a close-up view of an eggplant with the tip camera.\n"
    "Reasoning: \nI need to check the occupancy map to see where the eggplants are located.\n"
    "I obtained the occupancy map and found that there are some eggplant plants at (3.0, -2.0) on the map. "
    "I will set the manipulator to the home position for safe navigation.\n"
    "The manipulator is now in the home position. I will navigate to (3.0, -2.0).\n"
    "I have reached the target location. Now I will check the front camera image to see if there are eggplant plants in front of me.\n"
    "The front camera image shows a wall. I will get the robot-centric map to check where the eggplant plants are located relative to me.\n"
    "The robot-centric map shows some eggplant plants northwest of the robot frame. I will rotate in place 135 degrees counterclockwise. No forward motion is needed.\n"
    "I have rotated successfully. Now I'll get a front camera image to see if there are eggplants in front of me.\n"
    "The front camera image shows that there are eggplants ahead. I will move the manipulator to the scanning position to get a better view.\n"
    "Now I will check the tip camera image to see if I can see an eggplant.\n"
    "The tip camera image now shows an eggplant clearly at pixel coordinates (250, 400). I will center the tip camera on these coordinates.\n"
    "Now the eggplant  is visible in the center of the image, but I could get closer. I will move the tip camera forward.\n"
    "I wasn't able to move forward but the eggplant is clearly visible. I will notify the human about it.\n"

    "Example 3. \n"
    "Task: Go to the eggplant plants and get a close-up view of an eggplant with the tip camera.\n"
    "Reasoning: \nI need to check the occupancy map to see where the eggplants are located.\n"
    "I obtained the occupancy map and found that there are some eggplant plants at (3.0, -2.0) on the map. \n"
    "I will set the manipulator to the home position for safe navigation.\n"
    "The manipulator is now in the home position. I will navigate to (3.0, -2.0).\n"
    "I have reached the target location. Now I will check the front camera image to see if there are eggplants in front of me.\n"
    "The front camera image shows a plant, but it doesn't look like an eggplant plant. I will get the robot-centric map to check where the eggplant plants are located relative to me.\n"
    "The robot-centric map shows some eggplant plants to the south of the robot frame. I will rotate in place 90 degrees clockwise. No forward motion is needed.\n"
    "I have rotated successfully. Now I will check the front camera image to see if there are eggplants in front of me.\n"
    "The front camera does not show any eggplants. This was probably a false positive in the map. I will check the global occupancy map to find another cluster of eggplants.\n"
    "The occupancy map shows another cluster of eggplant plants at (2.0, 4.0). I will navigate to (2.0, 4.0).\n"
    "I have reached the target location. Now I will check the front camera image to see if there are eggplants in front of me.\n"
    "The front camera image shows that there are eggplants ahead. I will move the manipulator to the scanning position to get a better view...\n"

    "Example 4. \n"
    "Task: Go to the eggplant plant and get a close-up view of an eggplant with the tip camera.\n"
    "Reasoning: \nI need to check the occupancy map to see where the eggplant plants are located.\n"
    "I obtained the occupancy map and found that there are some eggplant plants at (3.0, 4.0) on the map. I will set the manipulator to the home position for safe navigation.\n"
    "The manipulator is now in the home position. I will navigate to (3.0, 4.0).\n"
    "I have reached the target location. Now I will check the front camera image to see if there are eggplant plants in front of me.\n"
    "The front camera image shows that there are eggplant plants ahead. I will move the manipulator to the scanning position to get a better view.\n"
    "Now I will check the tip camera image to see if I can see an eggplant.\n"
    "The tip camera image now shows an eggplant clearly at pixel coordinates (100, 350). I will center the tip camera on these coordinates.\n"
    "After trying to center the eggplant, it is not centered yet. I will try to center the tip camera at pixel coordinates (400,300) where the eggplant is.\n"
    "Now the eggplant is visible in the center of the image, but I could get closer. I will move the tip camera forward.\n"
    "I will try to move further forward to get closer to the eggplant.\n"
    "After moving the camera forward, the eggplant is now clearly visible. I will notify the human about it.\n"

    
    "Example 5. \n"
    "Task: Go to the eggplant plants and get a close-up view of an eggplant with the tip camera.\n"
    "Reasoning: \nI need to check the occupancy map to see where the eggplant plants are located.\n"
    "I obtained the occupancy map and found that there are some eggplant plants at (2.0, 4.0) on the map. "
    "I will set the manipulator to the home position for safe navigation.\n"
    "The manipulator is now in the home position. I will navigate to (2.0, 4.0).\n"
    "I have reached the target location. Now I will check the front camera image to see if there are eggplants in front of me.\n"
    "The front camera image shows that there are eggplants ahead. I will move the manipulator to the scanning position to get a better view.\n"
    "Now I will check the tip camera image to see if I can see an eggplant.\n"
    "The tip camera image shows an eggplant partially visible at the bottom. I will move the tip camera downward to get a better view.\n"
    "Moving the tip camera downward failed. I will center the bottom part of the image at coordinates (320, 480) as a second alternative.\n"
    "The tip camera image now shows an eggplant clearly at pixel coordinates (300, 450). I will center the tip camera on these coordinates...\n"

    "Example 6. \n"
    "Task: Go to the eggplant plants and get a close-up view of an eggplant with the tip camera.\n"
    "Reasoning: \nI need to check the occupancy map to see where the eggplant plants are located.\n"
    "I obtained the occupancy map and found that there are some eggplant plants at (1.0, 2.0) on the map. "
    "I will set the manipulator to the home position for safe navigation.\n"
    "The manipulator is now in the home position. I will navigate to (1.0, 2.0).\n"
    "I have reached the target location. Now I will check the front camera image to see if there are eggplants in front of me.\n"
    "There are some eggplants visible in the front camera image, but they are far away. "
    "I need to check the robot-centric map to see if I can get a little closer.\n"
    "The robot-centric map shows eggplants in front of me, but they are far away. "
    "I will move forward 0.5 meters. No rotation is needed since the eggplants are directly in front of me.\n"
    "I have moved forward 0.5 meters. Now I will check the front camera image again to see if I can get a better view of the eggplants.\n"
    "The front camera image shows that there are eggplants close to me. I will move the manipulator to the scanning position to get a better view...\n"


)


demonstrations={
    "navigation_manipulation_mode_v2": navigation_manipulation_mode_v2_demonstrations,
    "navigation_manipulation_mode_v3": navigation_manipulation_mode_v3_demonstrations,
}